### ISSUE TITLE
Waiting for reply of `initialized` before continuing

### ISSUE THREAD

**Issue by rezass** [FurqanSoftware/codemirror-languageserver#21]
Hi all,

Looking at https://github.com/latex-lsp/texlab/issues/805#issuecomment-1290233427, it seems that the `initialized` should be serialized after `initialize` and before sending any other requests. Currently it sends the `textDocument/didOpen` after `initialize`.

**Comment by hjr265** [comment]
I have just deployed an update and released it into NPM. This update should defer the initialization of the plugin (which is when "textDocument/didOpen" is emitted) until the client itself is ready (which is when "initialized" is emitted).

![image](https://user-images.githubusercontent.com/348107/198691961-ef597302-c22f-45be-a180-b570fc358d77.png)

Please feel free to reopen if the issue persists.
