### ISSUE TITLE
Issue with wrong diagnostic info position

### ISSUE THREAD

**Issue by bushev** [FurqanSoftware/codemirror-languageserver#3]
Hey @hjr265,

Thanks for the great usage example!!!

Sometimes, I could see the error that says that a position in a code is wrong to set diagnostics data. It 100% happens when I adding something by clicking to autocomplete tooltip and then trying to remove it with backspace as the end of the document.

Do you know, is it is some known issue?

![image](https://user-images.githubusercontent.com/7535766/116919117-d48def00-ac1e-11eb-9d51-dc1cb931fbbf.png)

**Comment by hjr265** [comment]
Thanks for reporting this @bushev. I have seen similar stack traces being captured from one of my projects using this in production. Although, I wasn't able to reproduce the issue reliably.

I will give this a try and if I can reproduce it, solving it should be easy.

**Comment by hjr265** [comment]
@bushev Spot on! Thank you for the pull request.
