### ISSUE TITLE
What is the proper way to import with Rollup?

### ISSUE THREAD

**Issue by yonihemi** [FurqanSoftware/codemirror-languageserver#5]
Thanks for what looks like an amazing plugin.

I'm trying to import using the [most minimal example possible](https://github.com/yonihemi/try-codemirror-languageserver) and getting this error:
```
[!] Error: 'CompletionItemKind' is not exported by node_modules/vscode-languageserver-protocol/lib/node/main.js, imported by node_modules/codemirror-languageserver/dist/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/codemirror-languageserver/dist/index.js (7:9)

```

I went down the rabbit-hole of that link, leading to a removed option and many open issues in Rollup's repo, and the commonjs plugin which didn't seem to work.

Appreciate any tips on the required config/plugins to get this up and running.

**Comment by deadmendontlie** [comment]
Also stumped by this issue since I am new to js and rollup. @hjr265 if you don't mind giving an explanation for this error or have any input that would be great.

**Comment by SeizureSaladd** [comment]
This seems like an old issue but I'm also experiencing the same problem and I'm wondering if there's a fix?
