### ISSUE TITLE
how to connect to tcp instead of web socket?

### ISSUE THREAD

**Issue by tirumalavasu** [FurqanSoftware/codemirror-languageserver#6]
In my case i have tcp for my language server, how to connect to tcp instead of web socket.

**Comment by hjr265** [comment]
@tirumalavasu You will have to put a proxy in between that will allow the web browser to connect using WebSocket, and the proxy will interact with the LSP server over TCP. 

https://hjr265.me/blog/codemirror-lsp/#language-server-over-websocket
