### ISSUE TITLE
Lua language server not working: `Loading workspace (0/0)`

### ISSUE THREAD

**Issue by arnoson** [FurqanSoftware/codemirror-languageserver#9]
I would like to switch from monaco to codemirror 6, but somehow I can't get the lua language server to work. I'm using sumneko's https://github.com/sumneko/lua-language-server/.

The same setup is working with monaco editor https://github.com/arnoson/monaco-lua-example (linux only for now).
Here I put together a simple setup illustrating the issue:
https://github.com/arnoson/codemirror-lua (lua has to be installed for the language server to work)

Do you have any idea what the problem could be or where I might have an error in my codemirror editor setup?

**Comment by arnoson** [comment]
Sumneko helped me a lot investigating the problem (https://github.com/sumneko/lua-language-server/issues/981). I created a PR that would fix this issue.

**Comment by hjr265** [comment]
Fixed through 04a2ca92a61bde2e84809ea58d8566b1d0781545 and c7ed3b2369634a685ccc317130f4f97029d9c675. Please use the latest version from NPM: 1.6.0.

**Comment by arnoson** [comment]
I have the same problem again (`Loading workspace (0/0)`) as the client isn't responding to all request anymore. Seems that your fix has been removed, is there any reason why?

**Comment by hjr265** [comment]
@arnoson Sorry, looks like this was accidentally dropped in a recently merged PR.

I am pushing a fix shortly.

**Comment by hjr265** [comment]
Published v1.8.1 with the fix restored.
